services:
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: socket-proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      LOG_LEVEL: info
      CONTAINERS: 1
      IMAGES: 1
      EXEC: 1
      POST: 1
      NETWORKS: 1
      ALLOW_START: 1
      ALLOW_STOP: 1
      ALLOW_RESTARTS: 1
      VOLUMES: 0
      SERVICES: 0
      TASKS: 0
      NODES: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket-proxy
